export type OrigFile = {
  categories: string
  date_added: string
  date_available: string
  date_modified: string
  height: number
  image_name: string
  length: number
  length_unit: string
  manufacturer: string
  'meta_description(ru)': string
  'meta_title(ru)': string
  minimum: number
  model: string
  'name(ru)': string
  points: number
  price: number
  product_id: number
  quantity: number
  seo_keyword: string
  shipping: string
  sku: string
  sort_order: number
  status: string
  stock_status_id: number
  store_ids: number
  subtract: string
  tax_class_id: number
  weight: number
  weight_unit: string
  width: number
}